import std/[strutils, unittest]
when defined(nimormPostgresIntegration):
  import std/os

import nimorm

model PgRecord:
  name = stringField(maxLength = 100)
  amount = decimalField(precision = 10, scale = 2)

  meta:
    tableName = "pg_records"

suite "PostgreSQL backend":
  test "compiles PostgreSQL placeholders and dialect types":
    let fakeDb = Database(backend: postgresBackend)
    let query = PgRecord.objects(fakeDb)
      .filter((it.name == "value") and (it.amount >= decimal("10.00")))
    let compiled = query.toSql()
    check "$1" in compiled.sql
    check "$2" in compiled.sql
    check "value" notin compiled.sql
    check "NUMERIC(10, 2)" in schemaSql(PgRecord, postgresBackend)
    check "GENERATED BY DEFAULT AS IDENTITY" in
      schemaSql(PgRecord, postgresBackend)

  when not defined(nimormPostgres):
    test "reports the compile-time backend gate clearly":
      expect ConnectionError:
        discard openPostgres(
          host = "localhost",
          port = 5432,
          database = "test",
          user = "test",
          password = "must-not-appear")

  when defined(nimormPostgresIntegration):
    test "executes CRUD against configured PostgreSQL":
      let db = openPostgres(
        host = getEnv("NIMORM_PG_HOST", "localhost"),
        port = parseInt(getEnv("NIMORM_PG_PORT", "5432")),
        database = getEnv("NIMORM_PG_DATABASE"),
        user = getEnv("NIMORM_PG_USER"),
        password = getEnv("NIMORM_PG_PASSWORD"))
      defer: db.close()
      discard db.execute("DROP TABLE IF EXISTS \"pg_records\"")
      db.createTables(PgRecord)
      let saved = db.insert(PgRecord(
        name: "parameterized",
        amount: decimal("12.50")))
      check saved.id > 0
      check db.get(PgRecord, saved.id).name == "parameterized"
